### PR TITLE
Feature/108 read data from docs

### PR DESCRIPTION
**Pull request by zenzeii**

### CODE REVIEW

**Comment by jtshark** [comment]
is there already somewhere a documentation which file must be inserted where as tokens (I was not able to find it), to let run the program?

**Comment by zenzeii** [comment]
> is there already somewhere a documentation which file must be inserted where as tokens (I was not able to find it), to let run the program?

Doc is WIP. But the tokens you can find in sync.com as always:)

**Comment by zenzeii** [comment]
@jtshark basically you just need to put the client_secrets.json in 'Data_Processing' folder from sync

**Review by jtshark — APPROVED** [review]

**Comment by jtshark** [comment]
The code looks good and I was able to run it 👍

**Pull request merged**
