### PR TITLE
Feature/110 text chunking

### PR DESCRIPTION
**Pull request by emuguy1**
adds functionality to chunk the data before passing it to supabase.

additional stuff: 
- names are now fetched and mapped to the messages from slack
- reworked the autolinter

### CODE REVIEW

**Comment by emuguy1** [comment]
@Kadi-7 @zenzeii As you can see we changed the pdf_reader in a way, that the pdf reader doesn't return the DataInformation List but the text. You were right this is better as the id naming shema can be set by the preprocessor and not the pdf reader.

**Comment by emuguy1** [comment]
@JessePalarus, @amela16, @Kadi-7, @zenzeii  We experimented a bit with our LLM and found the following two issues:
- When names are in texts, deepL will translate them but not necessarily backward when giving an answer. Example: try my last name( Erben) It will translate it often to Heirs. This can and sometimes already leads to errors.
- We added a dataset from Slack where I wrote something about cats. When running and asking for information about that, we see, that we get the right context(Supabase dataset) but the LLM still answers, that he has insufficient information.

If there are ideas or information, please answer. Else I would ask @tkonheiser and @SaraElBrak to maybe create tickets for this, for the next sprint, so we can investigate this.

**Comment by zenzeii** [comment]
Thanks for taking care of this issue. The code looks good! 😊
However when we use the function transform_text_to_chunks() for confluence it doesn't chunk correctly as described here https://github.com/orgs/amosproj/projects/17?pane=issue&itemId=29851702 

I think the problem must lay somewhere here:
image

**Comment by tkonheiser** [comment]
> Issue and Bug Report are created. @emuguy1 Please have a look at [Issue 129](https://github.com/amosproj/amos2023ss03-qachat/issues/129) and refine the steps to reproduce the error or let me know some more details, especially the message about cats and the corresponding question to the Slackbot.

**Pull request merged**
