### PR TITLE
adds a small unit test suite for chunking

### PR DESCRIPTION
**Pull request by Felix-012**
as a small addition to chunking, this would add a few basic tests to test chunking behavior

### CODE REVIEW

**Comment by jtshark** [comment]
For me there is a problem when I try to run the the locally.

The test will not run, I think that this has to do something with the working directory.
When I set the working directory to the Testing folder, then it can not find the tokens.env. (At least for me this is under QAChat/tokens.env)

And when I set the working directory to QAChat/Data_Processing then it can find the tokens.env. But then the dummydata is not found.

So a few fixes that should work (for how I placed the tokens.env): 

1. move the tokens.env to the main folder. and then use Testing/ QAChat as a working directory. If we do this then we should update our build process guide.

2. We move the Testing folder into QAChat (then we have to update the github actions)

3. We load the relativ path tokens.env or the dummy data differently, such that we can set the working directory to a fixed folder

But do you possibly have another solution there? And what do you use as your working directory and where is your tokens.env to let the test run?

**Comment by amela16** [comment]
Hey, I wanted to share a friendly tip for documenting your functions and methods. Instead of commenting above the function definition, it's more conventional to use docstrings (""" """).

**Comment by Felix-012** [comment]
> For me there is a problem when I try to run the the locally.
> 
> The test will not run, I think that this has to do something with the working directory. When I set the working directory to the Testing folder, then it can not find the tokens.env. (At least for me this is under QAChat/tokens.env)
> 
> And when I set the working directory to QAChat/Data_Processing then it can find the tokens.env. But then the dummydata is not found.
> 
> So a few fixes that should work (for how I placed the tokens.env):
> 
>     1. move the tokens.env to the main folder. and then use Testing/ QAChat as a working directory. If we do this then we should update our build process guide.
> 
>     2. We move the Testing folder into QAChat (then we have to update the github actions)
> 
>     3. We load the relativ path tokens.env or the dummy data differently, such that we can set the working directory to a fixed folder
> 
> 
> But do you possibly have another solution there? And what do you use as your working directory and where is your tokens.env to let the test run?

Well I basically did option 1, I just thought it was a local problem for me so I left it as is. Sorry I should have mentioned / communicated that. I would also suggest to do it like this, since we only would have to adapt the paths then which seems the easiest way to me personally.

**Comment by Felix-012** [comment]
> Hey, I wanted to share a friendly tip for documenting your functions and methods. Instead of commenting above the function definition, it's more conventional to use docstrings (""" """).

Personally I think that the functions can be left without comments since its rather obvious what they do. Or would you prefer comments here?

**Review by emuguy1 — APPROVED** [review]

**Review by jtshark — APPROVED** [review]

**Pull request merged**
