### PR TITLE
Refactoring/156 final code clean

### PR DESCRIPTION
**Pull request by jtshark**

### CODE REVIEW

**Comment by amela16** [comment]
Looks good!

**Comment by Felix-012** [comment]
yeah looks good to me too. maybe two things: do you guys think we should add some more comments to functions or is it fine as it is?
also maybe we should remove the unneeded main functions we had for testing purposes since they make the code look somewhat unclean imo

**Comment by jtshark** [comment]
> yeah looks good to me too. maybe two things: do you guys think we should add some more comments to functions or is it fine as it is? also maybe we should remove the unneeded main functions we had for testing purposes since they make the code look somewhat unclean imo

1. Do you have any functions is mind? Most of the imporntant functions should have python doc, and (at least for me) this would be enough

2. I would not removed the main functions for the reasson, that in the build documentation of some parts we wrote, that the use can try out if everthing workes by running the corrsponding test function. So I think this is a nice addition that a user can test if the installation of a small compoent worked, by simply running the main function.

Is it fine for you @Felix-012 ?

**Comment by Felix-012** [comment]
yeah alright makes sense. everything fine by me

**Pull request merged**
