### PR TITLE
Feature/52 test deepl api

### PR DESCRIPTION
**Pull request by emuguy1**
added a basic deepL tranlation service and tested some measurements to judge usability of deepL

### CODE REVIEW

**Comment by jtshark** [comment]
The deepL translator file has no load_data_from_csv method for me,
but in the translation_tests, it is used in the import in line 6.

**Comment by Felix-012** [comment]
this should be fixed now

**Review by jtshark — APPROVED** [review]

**Comment by emuguy1** [comment]
Edited it so that now the tokens are placed in the super folder QAChat and added that question is translated to english and answer translated into german

**Comment by emuguy1** [comment]
@tkonheiser This could be improved to answer in the language that the question was answered. DeepL therefore returns you the recognized language and we maybe could use it to translate it back into it.

**Pull request merged**
