### PR TITLE
Feature/140 supported database

### PR DESCRIPTION
**Pull request by Felix-012**
adds a local database for our project

### CODE REVIEW

**Comment by amela16** [comment]
Hey, great job! I tried it out using dummy data and Slack data, and everything worked smoothly. However, I have a suggestion for improvement. It would be helpful to have a view into the database for better transparency and easier debugging. 
Also, I have a question about data deletion. How can I remove data from the database to avoid duplicate datasets? 
Thank you!

**Comment by Felix-012** [comment]
yeah some visualization would be a good idea, I'll add a pretty print method this week I think. 
well the delete syntax is weaviate_client.batch.delete_objects("index_name", where_filter) 
(for filter design see https://weaviate.io/developers/weaviate/search/filters). But I could add a function that abstracts that process / makes it simpler if you think that is a good idea.

**Comment by amela16** [comment]
That feature would be great!

Based on the visualization, I believe it would be a more practical approach to write the data from the database into a text file instead of displaying it in the console. This way, it would be easier to work with the data, particularly when dealing with a large amount of data.

**Comment by zenzeii** [comment]
Thanks for the work guys!
I also tried but looks like windows is not supported :(
image


Also is there a documentation for weaviate? Like we had one before for supabase. In wiki page I couldn't find it.

Also in the comments above I agree. Since how I understand is that weaviate doesn't have a webui for showing the database like supabse right?

**Comment by Felix-012** [comment]
we have written a documentation for setting up the database in google cloud (https://github.com/amosproj/amos2023ss03-qachat/wiki/Google-Cloud-DB-Setup). Locally there is nothing to set up with weaviate, you can just run it (unless you're on windows, which I sadly did not consider). I think for supabase we only had creating an account and setting up tokens in the docu, which is not needed anymore ofc.

Yeah it doesn't have a webUI, that would kinda defeat the point why we switched in the first place I guess.

**Comment by Felix-012** [comment]
so I've added a method that prints an index as a table that can be used via SSH in google cloud.
if you want to see all existing indices and their properties you just need to call "python db_info.py" and for example you want to see all entries from embeddings you need to write  "python db_info.py Embeddings" and if you want e.g. all entries from embeddings after a certain timestamp you can write  "python db_info.py Embeddings  2GreaterThan2023-07-03T14:09:12.584293". The number at the front is the index of the property, so there is a 2 here because "last_changed" is the third property of Embeddings (you can check this by running "python db_info.py"). In general any string would work of the form <property_index><operator><value> .

**Comment by zenzeii** [comment]
@amela16 and I we tested the bot with new vector database and some confluence data where we know the answer is in confluence. Unfortunately we encountered some problems. This is what we get from the gcp console: 
image

But the same problem appears when we asked question (with the slack data) where it used to work before.

Other than that Thank you @Felix-012 for implementing the table making it more visual:)

**Comment by emuguy1** [comment]
@zenzeii is this happening every time and especially is it leading to a crash or only sometimes?
I cant really find something on that topic. I only found a GitHub Issue  [https://github.com/weaviate/weaviate/issues/1968](https://github.com/weaviate/weaviate/issues/1968) that sound very similar but unfortunately doesn't supply an solution.
Thanks in advance

**Comment by zenzeii** [comment]
We tried on @amela16 's machine. First asking questions about your cat that you mentioned in Slack. Unfortunately the bot told us that it does not have the information although in the gcp console it found your slack message about your cat.

Then we asked about something from confluence and then the error above appeared and in slack it only shows "..." and nothing else.

Then we asked again about you cat and it kept responding with just "..." and same error although before it resonded diffrently.

We only tried it twice both the same output. I dont know if this is a crash falls under the category crash or not.

**Pull request merged**
