### PR TITLE
tried different LLM and decided on one in the end

### PR DESCRIPTION
**Pull request by amela16**
We have tested various LLMs and prompts to determine which are most suitable. In doing so, we generated various questions and the associated context to test the LLMs. In addition, we optimized the parameters to improve the performance of the models.

### CODE REVIEW

**Comment by Felix-012** [comment]
so it seems the best one was the uncensored version of our previous llm? was there any significant performance improvement or is it more or less the same?

**Comment by amela16** [comment]
Hi @Felix-012 the bigger one was good too, but too big for google cloud. Before the LLM was not able to answer the question based on the context (your example with the cat). Now we are able to answer questions based on context. We added a repeat_penalty and adapted the prompt. We also tried different things out for example we tried out if we get better results if the LLM discuss about answer...

We tried out this models:
- wizard-mega-13B-GGML
- Longchat-13B-GGML
- WizardLM-33B-V1.0-Uncensored-GGML
- WizardLM-13B-V1.0-Uncensored-GGML

**Comment by emuguy1** [comment]
Is there a particular reason why it couldn't use the context or was it just the model?
And I saw you increased the GPU layers. Does that mean it can run faster or does this generally have no effect on performance and more on accuracy?

**Comment by amela16** [comment]
@emuguy1 with similarity search we were able to find the correct context. However, the LLM failed to comprehend the context. We don't know why, LLM's are hard to understand. The process of Parameter Finetuning involved guesswork, leading us to increase the layersize as well.

**Pull request merged**
